1. np.sort()

In [2]:
import numpy as np

In [3]:
a=np.random.randint(1,100,15)
a

array([72, 14, 60, 72,  5, 89, 66, 65, 17, 19, 61, 86, 70, 15, 36])

In [4]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[21, 54,  6, 83],
       [ 6,  1, 95, 64],
       [53, 79, 62, 65],
       [59, 67, 13, 81],
       [84, 10, 73, 18],
       [69, 10, 53, 32]])

In [5]:
np.sort(a)

array([ 5, 14, 15, 17, 19, 36, 60, 61, 65, 66, 70, 72, 72, 86, 89])

In [6]:
np.sort(a)[::-1]

array([89, 86, 72, 72, 70, 66, 65, 61, 60, 36, 19, 17, 15, 14,  5])

In [7]:
np.sort(b, axis=1)   # sorted row-wise

array([[ 6, 21, 54, 83],
       [ 1,  6, 64, 95],
       [53, 62, 65, 79],
       [13, 59, 67, 81],
       [10, 18, 73, 84],
       [10, 32, 53, 69]])

In [8]:
np.sort(b, axis=0)  #col-wise

array([[ 6,  1,  6, 18],
       [21, 10, 13, 32],
       [53, 10, 53, 64],
       [59, 54, 62, 65],
       [69, 67, 73, 81],
       [84, 79, 95, 83]])

2. np.append(),  np.unique()

In [9]:
a

array([72, 14, 60, 72,  5, 89, 66, 65, 17, 19, 61, 86, 70, 15, 36])

In [10]:
np.append(a,200)

array([ 72,  14,  60,  72,   5,  89,  66,  65,  17,  19,  61,  86,  70,
        15,  36, 200])

In [11]:
b

array([[21, 54,  6, 83],
       [ 6,  1, 95, 64],
       [53, 79, 62, 65],
       [59, 67, 13, 81],
       [84, 10, 73, 18],
       [69, 10, 53, 32]])

In [12]:
np.append(b, np.ones((b.shape[0],1)), axis=1)

array([[21., 54.,  6., 83.,  1.],
       [ 6.,  1., 95., 64.,  1.],
       [53., 79., 62., 65.,  1.],
       [59., 67., 13., 81.,  1.],
       [84., 10., 73., 18.,  1.],
       [69., 10., 53., 32.,  1.]])

np.concatenate()

In [13]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

print(c)
print(d)


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [14]:
np.concatenate((c,d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.concatenate((c,d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [16]:
e=np.array([1,1,1,2,2,2,3,3,4,5])

In [17]:
np.unique(e)

array([1, 2, 3, 4, 5])

np.expand_dims()

In [18]:
a

array([72, 14, 60, 72,  5, 89, 66, 65, 17, 19, 61, 86, 70, 15, 36])

In [19]:
a.shape

(15,)

In [20]:
np.expand_dims(a, axis=1)

array([[72],
       [14],
       [60],
       [72],
       [ 5],
       [89],
       [66],
       [65],
       [17],
       [19],
       [61],
       [86],
       [70],
       [15],
       [36]])

In [21]:
np.expand_dims(a, axis=1).shape

(15, 1)

np.where

In [22]:
a

array([72, 14, 60, 72,  5, 89, 66, 65, 17, 19, 61, 86, 70, 15, 36])

In [23]:
# find indices with value >50
np.where(a>50)


(array([ 0,  2,  3,  5,  6,  7, 10, 11, 12]),)

In [24]:
# replace them with zero
np.where(a%2==0,0,a)

array([ 0,  0,  0,  0,  5, 89,  0, 65, 17, 19, 61,  0,  0, 15,  0])

np.argmax, np.argmin

In [25]:
a

array([72, 14, 60, 72,  5, 89, 66, 65, 17, 19, 61, 86, 70, 15, 36])

In [26]:
np.argmax(a)

np.int64(5)

In [27]:
np.argmin(a)

np.int64(4)

In [28]:
b

array([[21, 54,  6, 83],
       [ 6,  1, 95, 64],
       [53, 79, 62, 65],
       [59, 67, 13, 81],
       [84, 10, 73, 18],
       [69, 10, 53, 32]])

In [29]:
np.argmax(b, axis=0)

array([4, 2, 1, 0])

In [30]:
np.argmax(b, axis=1)

array([3, 2, 1, 3, 0, 0])

np.cumsum, np.cumprod

In [31]:
a

array([72, 14, 60, 72,  5, 89, 66, 65, 17, 19, 61, 86, 70, 15, 36])

In [32]:
np.cumsum(a)

array([ 72,  86, 146, 218, 223, 312, 378, 443, 460, 479, 540, 626, 696,
       711, 747])

In [33]:
b

array([[21, 54,  6, 83],
       [ 6,  1, 95, 64],
       [53, 79, 62, 65],
       [59, 67, 13, 81],
       [84, 10, 73, 18],
       [69, 10, 53, 32]])

In [34]:
np.cumsum(b, axis=0)

array([[ 21,  54,   6,  83],
       [ 27,  55, 101, 147],
       [ 80, 134, 163, 212],
       [139, 201, 176, 293],
       [223, 211, 249, 311],
       [292, 221, 302, 343]])

In [35]:
np.cumprod(a)

array([                  72,                 1008,                60480,
                    4354560,             21772800,           1937779200,
               127893427200,        8313072768000,      141322237056000,
           2685122504064000,   163792472747904000, -4360591417389807616,
        8353250035775844352, -3828457979329196032, -8697278739884195840])

np.percentile

In [36]:
a

array([72, 14, 60, 72,  5, 89, 66, 65, 17, 19, 61, 86, 70, 15, 36])

In [37]:
np.percentile(a,50)

np.float64(61.0)

In [38]:
np.median(a)

np.float64(61.0)

np.histogram

In [39]:
a

array([72, 14, 60, 72,  5, 89, 66, 65, 17, 19, 61, 86, 70, 15, 36])

In [40]:
np.histogram(a, bins=[0,50,100])

(array([6, 9]), array([  0,  50, 100]))

np.corrcoeff

In [41]:
salary=np.array([20000,40000,10000,80000])
experience=np.array([1,3,2,4])

np.corrcoef(salary, experience)

array([[1.        , 0.87576054],
       [0.87576054, 1.        ]])

np.isin

In [42]:
a

array([72, 14, 60, 72,  5, 89, 66, 65, 17, 19, 61, 86, 70, 15, 36])

In [43]:
items=[10,20,30,40,42,63,91]
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

np.flip

In [44]:
a

array([72, 14, 60, 72,  5, 89, 66, 65, 17, 19, 61, 86, 70, 15, 36])

In [45]:
np.flip(a)

array([36, 15, 70, 86, 61, 19, 17, 65, 66, 89,  5, 72, 60, 14, 72])

In [46]:
b

array([[21, 54,  6, 83],
       [ 6,  1, 95, 64],
       [53, 79, 62, 65],
       [59, 67, 13, 81],
       [84, 10, 73, 18],
       [69, 10, 53, 32]])

In [47]:
np.flip(b)

array([[32, 53, 10, 69],
       [18, 73, 10, 84],
       [81, 13, 67, 59],
       [65, 62, 79, 53],
       [64, 95,  1,  6],
       [83,  6, 54, 21]])

np.put

In [48]:
a

array([72, 14, 60, 72,  5, 89, 66, 65, 17, 19, 61, 86, 70, 15, 36])

In [49]:
np.put(a,[0,1],[350,120])
a

array([350, 120,  60,  72,   5,  89,  66,  65,  17,  19,  61,  86,  70,
        15,  36])

In [50]:
a

array([350, 120,  60,  72,   5,  89,  66,  65,  17,  19,  61,  86,  70,
        15,  36])

np.delete

In [51]:
a

array([350, 120,  60,  72,   5,  89,  66,  65,  17,  19,  61,  86,  70,
        15,  36])

In [52]:
np.delete(a,[0,1])

array([60, 72,  5, 89, 66, 65, 17, 19, 61, 86, 70, 15, 36])

In [53]:
a

array([350, 120,  60,  72,   5,  89,  66,  65,  17,  19,  61,  86,  70,
        15,  36])

Set functions

In [54]:
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])

In [55]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [56]:
np.intersect1d(m,n)

array([3, 4, 5])

In [57]:
np.setdiff1d(m,n)

array([1, 2])

In [58]:
np.setdiff1d(n,m)

array([6, 7])

In [59]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [62]:
np.in1d(m,10)

/tmp/ipykernel_2089/3337556509.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,10)


array([False, False, False, False, False])

np.clip

In [63]:
a

array([350, 120,  60,  72,   5,  89,  66,  65,  17,  19,  61,  86,  70,
        15,  36])

In [65]:
np.clip(a,a_min=25, a_max=75)

array([75, 75, 60, 72, 25, 75, 66, 65, 25, 25, 61, 75, 70, 25, 36])